name: Build and Run Tests
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE checkpoint;' -uroot -proot
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
        env:
          DATABASE_URL: 'mysql://root:root@l27.0.0.1:3306/checkpoint'
